### ISSUE TITLE
Move `pytest` to dev dependency group

### ISSUE THREAD

**Issue by fynnfluegge** [fynnfluegge/codeqai#25]
`pytest` is currently defined in default dependency group:
```toml
[tool.poetry.dependencies]
python = "^3.9"
tiktoken = "^0.4.0"
yaspin = "^3.0.0"
pytest = "^7.4.0"
```

Should be moved to a separate dev dependency group to exclude it from build.
